version: "3.9" # Version yml
services:
  my-redis:
    image: "redis:6.2.6"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - "my-redis-data:/data"
  my-api:
    image: "api-redis:5"
    depends_on:
      - my-redis # Wait until my-redis
    environment:
      - REDIS_HOST=redis://my-redis:6379
    ports:
      - "8080:3000"
volumes:
  my-redis-data:

