version: "3.9" # Version yml
services:
  my-redis:
    image: "redis:alpine"
  my-api:
    image: "api-redis:2"
    depends_on:
      - my-redis # Wait until my-redis
    environment:
      - REDIS_HOST=redis://my-redis:6379
    ports:
      - "8080:3000"
